name: CI Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ] # También queremos que corra al hacer merge a main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm' # <--- ¡Añade esto para velocidad!

      - name: 1. Install dependencies
        run: npm ci # Usa 'ci' en lugar de 'install' para pipelines

      - name: 2. Linter (ESLint)
        run: npm run lint --if-present

      - name: 3. Test (Jest)
        run: CI=true npm run test

      - name: 4. Build
        run: npm run build --if-present
